<?php

require_once '/home/chrisvandam/Documents/Projects/concrete5/web/concrete/libraries/base_view.php';

/**
 * Test class for BaseView.
 * Generated by PHPUnit on 2012-02-01 at 17:18:45.
 *
 * @package Tests
 * @category Concrete
 * @author Chris van Dam <chris@trace.nl>
 */
class BaseViewTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var BaseView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseView;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BaseView::getStyleSheet
     * @todo Implement testGetStyleSheet().
     */
    public function testGetStyleSheet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::addHeaderItem
     * @todo Implement testAddHeaderItem().
     */
    public function testAddHeaderItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::addFooterItem
     * @todo Implement testAddFooterItem().
     */
    public function testAddFooterItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getHeaderItems
     * @todo Implement testGetHeaderItems().
     */
    public function testGetHeaderItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getFooterItems
     * @todo Implement testGetFooterItems().
     */
    public function testGetFooterItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::outputHeaderItems
     * @todo Implement testOutputHeaderItems().
     */
    public function testOutputHeaderItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::outputFooterItems
     * @todo Implement testOutputFooterItems().
     */
    public function testOutputFooterItems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::field
     * @todo Implement testField().
     */
    public function testField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::enablePreview
     * @todo Implement testEnablePreview().
     */
    public function testEnablePreview()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::isPreview
     * @todo Implement testIsPreview().
     */
    public function testIsPreview()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::disableLinks
     * @todo Implement testDisableLinks().
     */
    public function testDisableLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::enableLinks
     * @todo Implement testEnableLinks().
     */
    public function testEnableLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::areLinksDisabled
     * @todo Implement testAreLinksDisabled().
     */
    public function testAreLinksDisabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getThemeHandle
     * @todo Implement testGetThemeHandle().
     */
    public function testGetThemeHandle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getTheme
     * @todo Implement testGetTheme().
     */
    public function testGetTheme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getThemePath
     * @todo Implement testGetThemePath().
     */
    public function testGetThemePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::setThemeDirectory
     * @todo Implement testSetThemeDirectory().
     */
    public function testSetThemeDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getThemeDirectory
     * @todo Implement testGetThemeDirectory().
     */
    public function testGetThemeDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::setThemeByPath
     * @todo Implement testSetThemeByPath().
     */
    public function testSetThemeByPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::post
     * @todo Implement testPost().
     */
    public function testPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::getCollectionObject
     * @todo Implement testGetCollectionObject().
     */
    public function testGetCollectionObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::setCollectionObject
     * @todo Implement testSetCollectionObject().
     */
    public function testSetCollectionObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::inc
     * @todo Implement testInc().
     */
    public function testInc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::editingEnabled
     * @todo Implement testEditingEnabled().
     */
    public function testEditingEnabled()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::disableEditing
     * @todo Implement testDisableEditing().
     */
    public function testDisableEditing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::enableEditing
     * @todo Implement testEnableEditing().
     */
    public function testEnableEditing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::setController
     * @todo Implement testSetController().
     */
    public function testSetController()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::section
     * @todo Implement testSection().
     */
    public function testSection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::url
     * @todo Implement testUrl().
     */
    public function testUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::action
     * @todo Implement testAction().
     */
    public function testAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::renderError
     * @todo Implement testRenderError().
     */
    public function testRenderError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::defaultExceptionHandler
     * @todo Implement testDefaultExceptionHandler().
     */
    public function testDefaultExceptionHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::setTheme
     * @todo Implement testSetTheme().
     */
    public function testSetTheme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::escape
     * @todo Implement testEscape().
     */
    public function testEscape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BaseView::render
     * @todo Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
