<?php

require_once '/home/chrisvandam/Documents/Projects/concrete5/web/concrete/libraries/view.php';

/**
 * Test class for View.
 * Generated by PHPUnit on 2012-02-01 at 17:19:18.
 *
 * @package Tests
 * @category Concrete
 * @author Chris van Dam <chris@trace.nl>
 */
class ViewTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new View;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers View::getInstance
     */
    public function testGetInstance()
    {
        $this->assertTrue(class_exists('View'));

        $this->assertInstanceOf('BaseView', View::getInstance());
        $this->assertInstanceOf('View', View::getInstance());
    }
}
?>
